### ISSUE TITLE
Java 14 & Java 8 conflict?

### ISSUE THREAD

**Issue by chland** [rayferric/dungeon-finder#2]
When I try to run the jar, I get the following error (on Windows using the latest JRE for Java 8):

```
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/rayferric/dungeonfinder/cli/DungeonFinderCLI has been compiled by a more recent version of the Java Runtime (class file version 58.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:757)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:601)
```
And pretty much the same on an Ubuntu-machine (except that the version number 52.0 is replaced by 55.0). 

As I don't know much about Java I googled a bit and found this thread on StackExchange: https://stackoverflow.com/questions/63634840/file-has-been-compiled-by-a-more-recent-version-of-the-java-runtime-error-sceneb - and as far as I understood you downgraded from 14 to 8, too? So it maybe a similar problem?

**Comment by rayferric** [comment]
Actually, I've compiled the **Java 8** compatible source with **JDK 14**. My mistake! :sweat_smile: The **1.2.1** JAR was updated to a **[Java 8 build](https://github.com/rayferric/dungeon-finder/releases/download/1.2.1/dungeon-finder-1.2.1-all.jar)** and now everything should work just fine.

**Comment by chland** [comment]
Thanks :)
