### ISSUE TITLE
Keep getting this error

### ISSUE THREAD

**Issue by BurringtunBurr** [rayferric/dungeon-finder#4]
I'm new to using this kind of thing. So maybe I fucked up. Please help me out, Using it on a 1.17 singleplayer world

Out of bounds type exception: 12 Last valid type was : TAG_COMPOUND
java.lang.RuntimeException: Well fuck
        at io.xol.enklume.nbt.NBTag.create(NBTag.java:60)
        at io.xol.enklume.nbt.NBTag.parseInputStream(NBTag.java:21)
        at io.xol.enklume.nbt.NBTCompound.feed(NBTCompound.java:17)
        at io.xol.enklume.nbt.NBTag.parseInputStream(NBTag.java:22)
        at io.xol.enklume.nbt.NBTCompound.feed(NBTCompound.java:22)
        at io.xol.enklume.nbt.NBTag.parseInputStream(NBTag.java:22)
        at io.xol.enklume.nbt.NBTCompound.feed(NBTCompound.java:17)
        at io.xol.enklume.nbt.NBTag.parseInputStream(NBTag.java:22)
        at io.xol.enklume.MinecraftChunk.<init>(MinecraftChunk.java:30)
        at io.xol.enklume.MinecraftRegion.getChunkInternal(MinecraftRegion.java:110)
        at io.xol.enklume.MinecraftRegion.<init>(MinecraftRegion.java:52)
        at io.xol.enklume.MinecraftWorld.getRegion(MinecraftWorld.java:56)
        at com.rayferric.dungeonfinder.task.FindDungeonsInRegionTask.run(FindDungeonsInRegionTask.java:24)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by rayferric** [comment]
Sadly, Dungeon Finder doesn't work on any version past 1.12.2. Hugobros3/Enklume takes care of parsing the save, and at this point, library seems abandoned. Guess I'll have to note this in the README... I'm sure there are other libraries out there that can help with newer formats, but back then I chose Enklume for its ease of use and as it fulfilled all my needs. Also, writing my own parser could be an option too? If I had the time and motivation though... I literally wrote this just to gain advantage after reverse engineering the seed on one of the SMP servers. 😒
